### ISSUE TITLE
Scrapping reddit.com

### ISSUE THREAD

**Issue by picklu** [picklu/redditriver#2]
It seems scrapping reddit.com without api is quite impossible.

**Comment by lwb4** [comment]
@picklu Why is that?

**Comment by picklu** [comment]
@lincoln-b It was my first impression of scrapping reddit.com after I failed to get any data from reddit.com using Python's urllib. If you have any idea of scrapping reddit.com/new using Python without reddit api then please suggest me.

**Comment by lwb4** [comment]
@picklu No clue, I was just curious. Do you have a problem using something like PRAW? If so, you can usually add ".json" to the end of a public web request to get a JSON file rather than straight HTML. Like https://www.reddit.com/new.json, for example.

**Comment by picklu** [comment]
@lincoln-b Thank you for the information. PRAW is a wrapper for Reddit API. But, I do not want to use any API. So, getting a  json file from the reddit.com is a good option. I tried to download a JSON file and load that in python JSON module. It worked as I wanted.
